# 1     AlienNoFrameskip-v4
# 2     AmidarNoFrameskip-v4
# 3     AssaultNoFrameskip-v4
# 4     AsterixNoFrameskip-v4
# 5     AsteroidsNoFrameskip-v4
# 6     AtlantisNoFrameskip-v4
# 7     BankHeistNoFrameskip-v4
# 8     BattleZoneNoFrameskip-v4
# 9     BeamRiderNoFrameskip-v4
# 10    BerzerkNoFrameskip-v4
# 11    BowlingNoFrameskip-v4
# 12    BoxingNoFrameskip-v4
# 13    BreakoutNoFrameskip-v4
# 14    CentipedeNoFrameskip-v4
# 15    ChopperCommandNoFrameskip-v4
# 16    CrazyClimberNoFrameskip-v4
# 17    DefenderNoFrameskip-v4
# 18    DemonAttackNoFrameskip-v4
# 19    DoubleDunkNoFrameskip-v4
# 20    EnduroNoFrameskip-v4
# 21    FishingDerbyNoFrameskip-v4
# 22    FreewayNoFrameskip-v4
# 23    FrostbiteNoFrameskip-v4
# 24    GopherNoFrameskip-v4
# 25    GravitarNoFrameskip-v4
# 26    HeroNoFrameskip-v4
# 27    IceHockeyNoFrameskip-v4
# 28    JamesbondNoFrameskip-v4
# 29    KangarooNoFrameskip-v4
# 30    KrullNoFrameskip-v4
# 31    KungFuMasterNoFrameskip-v4
# 32    MontezumaRevengeNoFrameskip-v4
# 33    MsPacmanNoFrameskip-v4
# 34    NameThisGameNoFrameskip-v4
# 35    PhoenixNoFrameskip-v4
# 36    PitfallNoFrameskip-v4
# 37    PongNoFrameskip-v4
# 38    PrivateEyeNoFrameskip-v4
# 39    QbertNoFrameskip-v4
# 40    RiverraidNoFrameskip-v4
# 41    RoadRunnerNoFrameskip-v4
# 42    RobotankNoFrameskip-v4
# 43    SeaquestNoFrameskip-v4
# 44    SkiingNoFrameskip-v4
# 45    SolarisNoFrameskip-v4
# 46    SpaceInvadersNoFrameskip-v4
# 47    StarGunnerNoFrameskip-v4
# 48    ALE/Surround-v5
# 49    TennisNoFrameskip-v4
# 50    TimePilotNoFrameskip-v4
# 51    TutankhamNoFrameskip-v4
# 52    UpNDownNoFrameskip-v4
# 53    VentureNoFrameskip-v4
# 54    VideoPinballNoFrameskip-v4
# 55    WizardOfWorNoFrameskip-v4
# 56    YarsRevengeNoFrameskip-v4
# 57    ZaxxonNoFrameskip-v4

python code_062_play_all_ALE_games.py \
    --gym-id "BreakoutNoFrameskip-v4" \
    --fps 60 \
    --zoom 2.0 \
    --seed 37 \
    --actuator 1 \
    --forpaper 1